# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Printer < Formula
  desc "A delightful CLI for printing things V2 version"
  homepage ""
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.1/printer-v2_0.0.1_darwin_amd64.tar.gz"
      sha256 "b9060dbe334af5fb12b73431b2f9aa80d20d17bca41260c237c54b2f940cd14e"

      def install
        bin.install "printer-v2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.1/printer-v2_0.0.1_darwin_arm64.tar.gz"
      sha256 "f99f4004ef8b426b107f86d6e2127a9efcb5db27c236d3269f814a9bc6ff6bf8"

      def install
        bin.install "printer-v2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.1/printer-v2_0.0.1_linux_amd64.tar.gz"
        sha256 "89223cc3028f4e8cb48925a05213d58b95adf86acf46b40a569716163108c9a2"

        def install
          bin.install "printer-v2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.1/printer-v2_0.0.1_linux_arm64.tar.gz"
        sha256 "af4cc90920a1bb77627c0cb51f67613157662a9f7fe5c2c43368885bf222f2ba"

        def install
          bin.install "printer-v2"
        end
      end
    end
  end
end
