# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Printer < Formula
  desc "A delightful CLI for printing things V2 version"
  homepage ""
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.2/printer-v2_0.0.2_darwin_amd64.tar.gz"
      sha256 "fa60b1f91eba62b08cba6a75252f371eb4364de10f255684dff8186f06e74be1"

      def install
        bin.install "printer-v2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.2/printer-v2_0.0.2_darwin_arm64.tar.gz"
      sha256 "3b475d3d290fa66dbbf277110712f2cdae991f80c35d280948d5dc8af941345b"

      def install
        bin.install "printer-v2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.2/printer-v2_0.0.2_linux_amd64.tar.gz"
        sha256 "50bcbb481f9e1466d52715b90952298ada1bf713fb04e59de03029035f7b7577"

        def install
          bin.install "printer-v2"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-v2-releases/releases/download/v0.0.2/printer-v2_0.0.2_linux_arm64.tar.gz"
        sha256 "f324ce0162021699cf1fb7457fa405c972a0b05469fca6ece07076c05eeb9026"

        def install
          bin.install "printer-v2"
        end
      end
    end
  end
end
